### ISSUE TITLE
User space application

### ISSUE THREAD

**Issue by karo9** [karo9/OSO#2]
Initially, we need something similar to the usbip program from USB/IP: an application with ability to start a listening socket and pass it to the kernel.

Additionally, we can implement a mechanism analogous to one found in the stub driver which is being used to receive data from user space application.

see: linux-3.19/drivers/usb/usbip/stub_dev.c - store_sockfd function.

**Comment by dolorem** [comment]
Dla mnie wygląda dość prosto, choć pewnie i tak potrzebowałbym czyjegoś nadzoru przy tym tasku.
Śmiech M.

**Comment by karo9** [comment]
Spoko, wrzuciłem już jakąś okrojoną implementację (branch start-code) z usbipd. Jeszcze trochę trzeba to popoprawiać - z grubsza na razie chcemy tylko aby tworzyła socketa, czekała na jakieś połączenie i pchała je przez sysfs do naszego modułu vudc. (warto rzucić okiem na oryginalny plik usbpid.c, oraz tools/usb/usbip/libsrc/usbip_host_driver.c)
